// @CODE:TODO-CRUD-001:DATA
/**
 * Todo Model
 *
 * Mongoose schema and model for Todo items
 *
 * Schema:
 * - id: String (UUID, auto-generated by MongoDB)
 * - title: String (required, 1-200 chars)
 * - description: String (optional, max 1000 chars)
 * - priority: String (enum: 'low', 'medium', 'high', default: 'medium')
 * - completed: Boolean (default: false)
 * - createdAt: Date (auto-generated)
 * - updatedAt: Date (auto-generated)
 *
 * @module models/todo
 * @see {@link https://docs.mongoosejs.com/|Mongoose Documentation}
 */

import mongoose from 'mongoose';

const todoSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, 'Title is required'],
      trim: true,
      maxlength: [200, 'Title cannot exceed 200 characters'],
    },
    description: {
      type: String,
      trim: true,
      maxlength: [1000, 'Description cannot exceed 1000 characters'],
    },
    priority: {
      type: String,
      enum: {
        values: ['low', 'medium', 'high'],
        message: 'Priority must be either low, medium, or high',
      },
      default: 'medium',
    },
    completed: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true, // Automatically adds createdAt and updatedAt fields
    versionKey: false, // Disable __v field
  }
);

// Create indexes for better query performance
todoSchema.index({ completed: 1 });
todoSchema.index({ createdAt: -1 });
todoSchema.index({ priority: 1 });
todoSchema.index({ priority: 1, completed: 1 }); // Compound index for common queries

// Instance methods for better encapsulation
/**
 * Mark todo as completed
 * @returns {Promise<Document>} Updated todo document
 */
todoSchema.methods.markAsCompleted = function() {
  this.completed = true;
  return this.save();
};

/**
 * Mark todo as incomplete
 * @returns {Promise<Document>} Updated todo document
 */
todoSchema.methods.markAsIncomplete = function() {
  this.completed = false;
  return this.save();
};

/**
 * Update todo priority
 * @param {string} newPriority - New priority value ('low', 'medium', 'high')
 * @returns {Promise<Document>} Updated todo document
 */
todoSchema.methods.updatePriority = function(newPriority) {
  this.priority = newPriority;
  return this.save();
};

/**
 * Get todo summary (title and priority)
 * @returns {Object} Summary object with title and priority
 */
todoSchema.methods.getSummary = function() {
  return {
    id: this._id,
    title: this.title,
    priority: this.priority,
    completed: this.completed,
    createdAt: this.createdAt,
    updatedAt: this.updatedAt
  };
};

// Static methods for common queries
/**
 * Find all todos sorted by priority and creation date
 * @param {Object} filter - Query filter (optional)
 * @returns {Promise<Array>} Array of todos
 */
todoSchema.statics.findByPriority = function(filter = {}) {
  // Use more efficient query with manual sorting for better performance
  const priorityOrder = { high: 3, medium: 2, low: 1 };

  return this.find(filter)
    .sort({ createdAt: -1 }) // First sort by creation date
    .exec()
    .then(todos => {
      // Then sort by priority in memory (faster for small datasets)
      return todos.sort((a, b) => {
        const priorityDiff = priorityOrder[b.priority] - priorityOrder[a.priority];
        if (priorityDiff !== 0) return priorityDiff;
        return new Date(b.createdAt) - new Date(a.createdAt);
      });
    });
};

/**
 * Find todos by completion status
 * @param {boolean} completed - Completion status to filter by
 * @returns {Promise<Array>} Array of todos
 */
todoSchema.statics.findByStatus = function(completed) {
  return this.find({ completed })
    .sort({ createdAt: -1 })
    .exec();
};

/**
 * Get todos statistics
 * @returns {Promise<Object>} Statistics object
 */
todoSchema.statics.getStats = async function() {
  const stats = await this.aggregate([
    {
      $group: {
        _id: null,
        total: { $sum: 1 },
        completed: {
          $sum: { $cond: [{ $eq: ['$completed', true] }, 1, 0] }
        },
        incomplete: {
          $sum: { $cond: [{ $eq: ['$completed', false] }, 1, 0] }
        },
        highPriority: {
          $sum: { $cond: [{ $eq: ['$priority', 'high'] }, 1, 0] }
        },
        mediumPriority: {
          $sum: { $cond: [{ $eq: ['$priority', 'medium'] }, 1, 0] }
        },
        lowPriority: {
          $sum: { $cond: [{ $eq: ['$priority', 'low'] }, 1, 0] }
        }
      }
    }
  ]);

  return stats[0] || {
    total: 0,
    completed: 0,
    incomplete: 0,
    highPriority: 0,
    mediumPriority: 0,
    lowPriority: 0
  };
};

// Create and export the model
const Todo = mongoose.model('Todo', todoSchema);

export default Todo;
